[connections.gsheets]
type = "service_account"
project_id = "quiz-cfa"
private_key_id = "c9042715669fa8c2e649f32a643983136ef385d5"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDI5PeKGsBJcL5B
KHwsrkwbGq22emwgPv6h+tvxHcmF2XEG7x4/UNpRuJlNPzXG0pDgtX9fjWP2megh
pxuLkQvdQKuuN6Qwok625qys3QD1iO8Bs2lN1Vq0uIpaV3X/K2xXpM9W3VTYAUAG
Q+tb33b/tw2c/TcTurTSzvw6uzKespim/3aUp604J+ZaLxYDq3evEbR/+fclrjy8
Oe3y3ZryXvMzNeLjDvQaPbhjUjXnAdya5uggb7ZGXNdhQen2ZQ0Q7ndFaJQUyyzr
b1z7Lam+d/Y7CJuptlNxVikb13SFYYnxaRmgfeGM1Vlpb4k/+LjYwC8eqHq6S7kT
v9WSeUQtAgMBAAECggEACnqbCOqlTg9h9S8h7wi2cpF9LzAKlNIEYTmfIGAf42n4
sdZmOwJCKRIaeQOLkA/qu7Xr63WKGdJkX+ECGFEcD9HwQpmnaFwHBBZbOncatjQK
14levE8dOKEJonW+c2117MptgEfyRYQnLUx8qeGpqOQJAz/YECDkjrx6PqwGE24A
zM/x0uYDxqwB76ppwy9yy1LFCArol77/xEdPOx7YW8fFHQYzELqxdqh147nqzpwa
C+HYqPzeqssJOpmj1NAzuMHNuvUlkzEtXqxw7Bd/9Ewtkp5sEzcq0w1Of8dbmaRL
XuwMBII5beR36g4cmUaaUBsuR/yyuMGbO3nrQxdklwKBgQDjYZL2bs7CKEQfXq1Q
MbYHF22k4G0aIcgS/OzLZC9J1o+Vd/fU7vysj7m9cxfZTr3Pm+invuwM+/QGPTfN
gMKYGrjwQwFYik04+z16SCu0JQxTZq2zFf6QaR53NJ9XXA3eJHfIJ7Bs9BtzoQg6
ESlRIU5F8LqNEORZA6fwTTUJawKBgQDiLfdK899iAWpXKekVkSp/n8x5Jw/nozaq
To3C7q4OaaUjVdKMSuITUZt9tsRWfVA+3yyj/hmcNfM+RyI61F0b9kg2aWtGJkZY
TCt5vj8Z0nljMOpW3+8sywZ9lqbhXU5aa4Vy1GiDTZXHfUpRED3ICugXJbGEQx8c
SMVtc39WxwKBgQDA2yetQPq5DzIIcWMKm79KcIKcz4V6HqD2CfRF5ql9NTD/k4tu
3W0OZ7EgkJfvxquThSdl77eCo8ir6gyEjut921x03EAt+s/Yvq+8Ia5/0tSLgJFf
Tg5mKeKfNNDZZciVW9UEvTUUlE8cWb8CkT+8AkXDaJSxxVwIa+NrG/EaFQKBgGv6
E7/FkxQfptu711mDdu18pUoFWvNzmKpPXB/+gDvDNaIb26s8KJeecwPeF/dOVdve
AVq8+Q75Nom5vd6l+VlbBvhq9VqE9To8CtlQ+KDkOS0gcg9NUspolk2oeTzHpZtH
D2tVehuNE38sEimG/mecxVYfmZKR1K1VFGN/KwCLAoGAZ6L97YtAwnagR/DcX7S5
ilhv/3JXgcmJnNanm+f+qQmfeU0J/3yPKZtomgGg2+dzlvEkpBHGn6NRIzvn4iyU
MmvHUG9lerSNhEh2IUyxZPulDjN3dAyJBhZGol+Mcc08xmg2akX6eu2wR3Atc+wV
Moj3sZT1YDZ4UjPFxtnmw9U=
-----END PRIVATE KEY-----
"""
client_email = "quiz-cfa@quiz-cfa.iam.gserviceaccount.com"
client_id = "103352601086011425530"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/quiz-cfa%40quiz-cfa.iam.gserviceaccount.com"
spreadsheet = "https://docs.google.com/spreadsheets/d/1RkeP21zPxgK1GFV1WmzUiaV6zN5HgxYxVKqYL4Rc1HI/edit#gid=0"
